#!/usr/bin/env node
/**
 * scripts/vscode-sync.ts
 *
 * Generates the root `.vscode/launch.json` and `.vscode/tasks.json` so that
 * debugging/running any package works from the workspace root, without
 * hand-maintaining package names in either file.
 *
 * === Why "generated" instead of truly dynamic ===
 * VS Code's launch.json/tasks.json are plain static JSON — there is no
 * built-in way to enumerate workspace packages at runtime (a `pickString`
 * input's `options` must be a literal array; a `command`-type input needs a
 * third-party extension to back it). So the approach here is the same one
 * `apps/vscode/scripts/docs` uses for README generation: dynamic at
 * generation time, static in the committed result. The real package
 * names/paths/kinds are read exactly once, in this script, via
 * `lib/workspace.ts` — nowhere else hardcodes them.
 *
 * When this runs:
 *   - after `pnpm install` (root `postinstall`), so adding/removing a package
 *     re-syncs automatically
 *   - manually via `pnpm vscode:sync`
 *   - in CI via `pnpm vscode:sync:check`, which regenerates and then
 *     `git diff --exit-code`s the result — catches a package being added
 *     without re-running sync (same idea as the docs:update CI check).
 */

import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { listWorkspacePackages, type WorkspacePackage } from "./lib/workspace.ts";

const ROOT = process.cwd();
const VSCODE_DIR = join(ROOT, ".vscode");

const generatedBanner = (file: string) =>
    `// Generated by \`pnpm vscode:sync\` (scripts/vscode-sync.ts). Do not edit by hand.\n` +
    `// Re-run that command after adding/removing/renaming a package under apps/ or packages/ to resync ${file}.\n` +
    `// CI verifies this file is in sync via \`pnpm vscode:sync:check\`.\n`;

interface VscodeTask {
    label: string;
    type: "shell";
    command: string;
    args?: string[];
    options?: { env?: Record<string, string> };
    group?: { kind: "build" | "test"; isDefault?: boolean };
    presentation?: Record<string, unknown>;
    problemMatcher?: unknown[];
}

interface LaunchConfig extends Record<string, unknown> {
    name: string;
    type: string;
    request: "launch" | "attach";
}

/** Grouping shown in tasks.json; purely cosmetic. */
const TASK_GROUP: Record<string, "build" | "test"> = {
    compile: "build",
    build: "build",
    watch: "build",
    rolldown: "build",
    lint: "build",
    "docs:update": "build",
    "docs:update:static": "build",
    vsce: "build",
    test: "test",
    "test:unit": "test",
    "test:e2e": "test",
    wdio: "test",
};

/** Only actions that actually exist on a given package's scripts get a task generated for them. */
const CANDIDATE_ACTIONS = [
    "dev",
    "build",
    "compile",
    "watch",
    "rolldown",
    "lint",
    "test",
    "test:unit",
    "test:e2e",
    "wdio",
    "vsce",
    "docs:update",
    "docs:update:static",
    "tauri",
];

function runTaskCommand(
    pkg: WorkspacePackage,
    action: string,
): { command: string; args: string[] } {
    return { command: "node", args: ["scripts/run.ts", action, `--target=${pkg.name}`] };
}

function buildTasksForPackage(pkg: WorkspacePackage): VscodeTask[] {
    const tasks: VscodeTask[] = [];

    for (const action of CANDIDATE_ACTIONS) {
        if (action === "tauri") {
            if (pkg.kind !== "tauri-app" || !pkg.scripts.tauri) continue;
        } else if (!pkg.scripts[action]) {
            continue;
        }
        const { command, args } = runTaskCommand(pkg, action);
        const isWatchLike = action === "watch" || action === "dev";
        tasks.push({
            label: `${pkg.name}: ${action}`,
            type: "shell",
            command,
            args,
            group: TASK_GROUP[action] ? { kind: TASK_GROUP[action] } : undefined,
            presentation: { panel: "dedicated", reveal: "always", clear: isWatchLike },
            problemMatcher: [],
        });
    }

    // apps/vscode's rolldown.config.ts switches build target based on process.env.TEST
    // (src/extension.ts vs tests/**). "test:unit" needs the latter, so this generates a
    // dedicated TEST=true compile task for the "Extension Tests" launch config below to use.
    if (pkg.kind === "vscode-extension" && pkg.scripts["test:unit"] && pkg.scripts.compile) {
        const { command, args } = runTaskCommand(pkg, "compile");
        tasks.push({
            label: `${pkg.name}: compile (tests)`,
            type: "shell",
            command,
            args,
            options: { env: { TEST: "true" } },
            group: { kind: "test" },
            presentation: { panel: "dedicated", reveal: "silent", clear: false },
            problemMatcher: [],
        });
    }

    return tasks;
}

function buildLaunchConfigsForPackage(pkg: WorkspacePackage): LaunchConfig[] {
    if (pkg.kind !== "vscode-extension") return [];

    const configs: LaunchConfig[] = [];
    const preLaunchTask = pkg.scripts.compile ? `${pkg.name}: compile` : undefined;

    configs.push({
        name: `Run Extension: ${pkg.name}`,
        type: "extensionHost",
        request: "launch",
        args: [`--extensionDevelopmentPath=\${workspaceFolder}/${pkg.relPath}`],
        outFiles: [`\${workspaceFolder}/${pkg.relPath}/out/**/*.{js,cjs}`],
        ...(preLaunchTask ? { preLaunchTask } : {}),
    });

    if (pkg.scripts["test:unit"]) {
        const testPreLaunchTask = pkg.scripts.compile ? `${pkg.name}: compile (tests)` : undefined;
        configs.push({
            name: `Extension Tests: ${pkg.name}`,
            type: "extensionHost",
            request: "launch",
            args: [
                `--extensionDevelopmentPath=\${workspaceFolder}/${pkg.relPath}`,
                `--extensionTestsPath=\${workspaceFolder}/${pkg.relPath}/out_test/index`,
            ],
            outFiles: [`\${workspaceFolder}/${pkg.relPath}/out_test/**/*.{js,cjs}`],
            env: { TEST: "true" },
            ...(testPreLaunchTask ? { preLaunchTask: testPreLaunchTask } : {}),
        });
    }

    return configs;
}

function buildGenericTask(pkgs: WorkspacePackage[]): { task: VscodeTask; inputs: unknown[] } {
    const task: VscodeTask = {
        label: "workspace: run action on package",
        type: "shell",
        command: "node",
        args: ["scripts/run.ts", "${input:pkgAction}", "--target=${input:pkgName}"],
        presentation: { panel: "dedicated", reveal: "always" },
        problemMatcher: [],
    };
    const inputs = [
        {
            id: "pkgName",
            type: "pickString",
            description: "Target package (generated from the pnpm workspace — do not hand-edit)",
            options: pkgs.map((p) => p.name),
        },
        {
            id: "pkgAction",
            type: "promptString",
            description: "Action to run (must exist in that package's package.json#scripts)",
        },
    ];
    return { task, inputs };
}

function writeJsonc(path: string, banner: string, data: unknown): void {
    writeFileSync(path, `${banner}${JSON.stringify(data, null, 2)}\n`, "utf-8");
}

function main(): void {
    const packages = listWorkspacePackages(ROOT).sort((a, b) => a.name.localeCompare(b.name));

    if (!existsSync(VSCODE_DIR)) mkdirSync(VSCODE_DIR, { recursive: true });

    const perPackageTasks = packages.flatMap(buildTasksForPackage);
    const { task: genericTask, inputs } = buildGenericTask(packages);
    writeJsonc(join(VSCODE_DIR, "tasks.json"), generatedBanner("tasks.json"), {
        version: "2.0.0",
        tasks: [...perPackageTasks, genericTask],
        inputs,
    });

    const configurations = packages.flatMap(buildLaunchConfigsForPackage);
    writeJsonc(join(VSCODE_DIR, "launch.json"), generatedBanner("launch.json"), {
        version: "0.2.0",
        configurations,
    });

    console.log(
        `✅ Regenerated .vscode/launch.json and .vscode/tasks.json from ${packages.length} package(s): ` +
            packages.map((p) => p.name).join(", "),
    );

    // Keep the generated output aligned with the repo's formatting rules (array collapsing, etc.) —
    // otherwise every local/CI `vp fmt` run would produce a diff against this script's raw
    // JSON.stringify output, and `vscode:sync:check` would never be able to converge.
    try {
        execFileSync(
            "vp",
            ["fmt", join(VSCODE_DIR, "launch.json"), join(VSCODE_DIR, "tasks.json")],
            {
                cwd: ROOT,
                stdio: "ignore",
                shell: true,
            },
        );
    } catch {
        console.warn(
            "⚠️  Could not run `vp fmt` on the generated .vscode files (vite-plus not installed?).",
        );
    }

    // settings.json: only guarantee it exists, never overwrite a developer's own configuration.
    const settingsPath = join(VSCODE_DIR, "settings.json");
    if (!existsSync(settingsPath)) writeFileSync(settingsPath, "{}\n", "utf-8");
}

main();
